pipeline {
    agent any

    environment {
        PROJECT_NAME = 'bezkoder-app'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/MuneebAhmadBhatti/devops-project/'  // Replace with your GitHub repository URL
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker-compose -p ${PROJECT_NAME} -f docker-compose.yml build'
                }
            }
        }
        
        stage('Deploy to AWS EC2') {
            steps {
                script {
                    sh 'docker-compose -p ${PROJECT_NAME} -f docker-compose.yml up -d'
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
